### ISSUE TITLE
NEW INDEX: NDMI

### ISSUE THREAD

**Issue by bpurinton** [davemlz/awesome-spectral-indices#2]
Please, complete the following information:

```python
NDMI=SpectralIndex(
    short_name='NDMI',
    long_name='Normalized Difference Moisture Index ',
    formula='(N - S1)/(N + S1)',
    reference='https://doi.org/10.1016/S0034-4257(01)00318-2',
    type='vegetation',
    date_of_addition='2021-12-01',
    contributor="https://github.com/bpurinton"
)
```

Example:

```python
SeLI=SpectralIndex(
    short_name='SeLI',
    long_name='Sentinel-2 LAI Green Index',
    formula='(RE4 - RE1) / (RE4 + RE1)',
    reference='https://doi.org/10.3390/s19040904',
    type='vegetation',
    date_of_addition='2021-04-08',
    contributor="https://github.com/davemlz"
)
```

This is a common index that is also listed on the Landsat pages: https://www.usgs.gov/core-science-systems/nli/landsat/normalized-difference-moisture-index

**Comment by davemlz** [comment]
Hi, @bpurinton! Thank you very much for your contribution to `awesome-spectral-indices`! :rocket: 

I have added the new index to the list and you can check it [here](https://github.com/davemlz/awesome-spectral-indices/blob/main/output/spectral-indices-table.csv) or in the [README](https://github.com/davemlz/awesome-spectral-indices).

The index will be available for the `spectral` module once the new version is released, and it can be used now with `eemont` (`spectralIndices()`) and `spyndex` (`computeIndex()`) by setting the argument `online=True`.

Cheers!

**Comment by bpurinton** [comment]
Thanks for a great resource. Really useful for teaching purposes (and research!).
